# Config file for MCDReforged

# MCDR的运行语言
# Language file need to be in lang/ folder, and encoded in utf8
# 举例:
#   en_us
#   zh_cn
language: zh_cn


# The working directory of the server. If you use default value server/ I will suggest you to put all the files related to the server to the server/ folder
working_directory: server


# The console command to start the server. Examples:
#   java -Xms1G -Xmx2G -jar minecraft_server.jar nogui
#   java -Djline.terminal=jline.UnsupportedTerminal -jar BungeeCord.jar
#   ./start.sh
#   start.bat
start_command: java -Xms1G -Xmx2G -jar minecraft_server.jar nogui


# The parser to parse the output of the server. Available options:
# vanilla_parser
#   for Vanilla / Carpet / Fabric server
#
# bukkit_parser
#   For Bukkit / Spiogt server with Minecraft version below 1.14, and Paper server in all version
#
# bukkit_parser_14
#   For Bukkit / Spiogt server with Minecraft version 1.14 and above
#
# forge_parser
#   For Forge server
#
# cat_server_parser
#   For CatServer server
#
# bungeecord_parser
#   for Bungeecord server
#
# waterfall_parser
#   for Waterfall server
#
parser: vanilla_parser


# the encoding / decoding format used to encode / decode message to the server. Choose the best method for your os. Examples:
#   utf8
#   gbk
# leave it blank for MCDR to auto detect system encoding
encoding:
decoding:


# if any command input to the console starts with the string below, MCDR will not send this command to server's stdin
# for example the default value is !! so these commands won't be sent to server's stdin
#   !!test
#   !!this is a command
console_command_prefix: '!!'


# rcon setting
# if enable, plugins can use rcon to query command from the server
enable_rcon: false
rcon_address: 127.0.0.1
rcon_port: 25575
rcon_password: password


# If set to true, MCDR will not start the console thread for handling console command input
# Don't change it to true unless you know what you are doing
disable_console_thread: false


# If set to true, if MCDR detects a newer version it will automatically download it
download_update: true


# Debug mode switch. Don't change it to true unless necessary
debug_mode: false

# Missing options down below
